[options]
addons_path = E:\workspace\gtgk\a-file-server\base_addons,E:\workspace\gtgk\a-file-server\my_addons,E:\data\my_file
admin_passwd = $pbkdf2-sha512$25000$FgIgxBijFKL0HkPIWWutVQ$3RR9v6XSsX.TI3uPFhI8RJ8//Dyw6v/Glr2nQZOLrx6jy8gwFWAuKLuLH2DzDGl0j.90cV2TjWKYconeEm38kA
agent = 
csv_internal_sep = ,
data_dir = E:\data_dir
db_host = localhost
db_maxconn = 64
db_name = file_v2
db_password = 123456
db_port = 5432
db_sslmode = prefer
db_template = template0
db_user = root
dbfilter = 
demo = {}
email_from = False
file_backup_path = E:\data_back
file_convert_url = http://127.0.0.1:8002
geoip_database = E:\usr\share\GeoIP\GeoLite2-City.mmdb
http_enable = True
http_interface = 
http_port = 9051
import_partial = 
limit-time-real = 999999999999
limit_memory_hard = None
limit_memory_soft = None
limit_request = None
limit_time_cpu = None
limit_time_real = None
limit_time_real_cron = None
list_db = True
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = info
logfile = 
longpolling_port = 9072
main_server_url = http://127.0.0.1:8088
max_cron_threads = 16
message_url = http://127.0.0.1:517
osv_memory_age_limit = False
osv_memory_count_limit = False
pass_passwd = DTCloud_E9CF8A43724A17FA15E22A28695FB89F
pg_path = 
pidfile = 
proxy_mode = False
reportgz = False
rvt_middle_dir = E:\data\middle_file
screencasts = 
screenshots = C:\Users\ADMINI~1\AppData\Local\Temp\2\dtcloud_tests
server_url = http://58.240.192.243:9003
server_wide_modules = base,web
smtp_password = False
smtp_port = 25
smtp_server = localhost
smtp_ssl = False
smtp_user = False
syslog = False
test_enable = False
test_file = 
test_tags = None
transient_age_limit = 1.0
translate_modules = ['all']
unaccent = False
upgrade_path = 
without_demo = False
workers = None

