[options]
addons_path = E:\workspace\gtgk\a-conversion-server\my_addons,E:\workspace\gtgk\a-conversion-server\base_addons

admin_passwd = dtcloud
db_host = 127.0.0.1
db_port = 5432
db_user = root
db_password = 123456
xmlrpc = True
xmlrpc_interface =
xmlrpc_port = 8002

server_url = http://10.201.97.20:8002
message_url = http://127.0.0.1:517
file_url = http://127.0.0.1:9051

max_cron_threads = 16
limit-time-real = 999999999999
data_dir = /data_dir


# dwg2dxf
dwg2dxf_exe_path = D:\dwg2dxf\tool\TeighaFileConverter.exe

# document2view
libre_office_path = E:\libreoffice\program\soffice.exe

# out error log path
log_file_rvt = E:\log\rvt2dxf
log_file_dwg = E:\log\dwg2dxf
log_file_document_libre = E:\log\document_libre2view
log_file_document_office = E:\log\document_office2view

revit_exe = C:\ProgramData\Bimangle\Bimangle.ForgeEngine.Revit\CLI\ForgeEngineRvtCLI.exe
dgn_exe = C:\ProgramData\Bimangle\Bimangle.ForgeEngine.Dgn\CLI\ForgeEngineDgnCLI.exe
navisworks_exe = C:\ProgramData\Bimangle\Bimangle.ForgeEngine.Navisworks\CLI\ForgeEngineNwCLI.exe

rvt_dt_bim_json_exe_2016 = D:\BIMinstall\revit2016\Revit 2016\DTbimjson.exe
rvt_dt_bim_json_exe_2017 = D:\BIMinstall\revit2017\Revit 2017\DTbimjson.exe
rvt_dt_bim_json_exe_2018 = D:\BIMinstall\revit2018\Revit 2018\DTbimjson.exe
rvt_dt_bim_json_exe_2019 = D:\BIMinstall\revit2019\Revit 2019\DTbimjson.exe
rvt_dt_bim_json_exe_2020 = D:\BIMinstall\revit2020\Revit 2020\DTbimjson.exe

rvt_element_json_exe_2016 = D:\BIMinstall\revit2016\Revit 2016\ModelCheck.exe
rvt_element_json_exe_2017 = D:\BIMinstall\revit2017\Revit 2017\ModelCheck.exe
rvt_element_json_exe_2018 = D:\BIMinstall\revit2018\Revit 2018\ModelCheck.exe
rvt_element_json_exe_2019 = D:\BIMinstall\revit2019\Revit 2019\ModelCheck.exe
rvt_element_json_exe_2020 = D:\BIMinstall\revit2020\Revit 2020\ModelCheck.exe

is_convert = False


