[options]
addons_path = E:\workspace\gtgk\a-message-server\base_addons

admin_passwd = dtcloud
db_host = 127.0.0.1
db_port = 5432
db_user = root
db_password = 123456
# db_name= JH2022_5_6_1
# db_name= XCJ_base_2022_5_50
# pg_path= C:\Program Files\PostgreSQL\13\bin
xmlrpc = True
xmlrpc_interface =
xmlrpc_port = 517

max_cron_threads = 16
limit-time-real = 999999999999
data_dir = /data_dir

server_url = http://127.0.0.1:517
main_server_url = http://127.0.0.1:8088





